### ISSUE TITLE
Roll up fails to resolve @tiptap/prosemirror-tables 

### ISSUE THREAD

**Issue by faizie17** [netchampfaris/frappe-ui-starter#3]
I am trying to use this starter with Frappe v14. I have created a app, installed it to a website and then cloned this repo using `npx degit` command mentioned in README. However, I am stuck with the below error when using with `yarn dev`:

![Screenshot from 2022-12-09 18-39-32](https://user-images.githubusercontent.com/92132180/206709694-03d3eff8-4cd7-4780-9975-c40582debcf9.png)

### `yarn build` results in the below error:

```bash
frappe@5e88fa44bcbc:/workspace/development/frappe-bench/apps/sampleclone/frontend$ yarn build
yarn run v1.22.19
$ vite build
vite v2.7.12 building for production...
✓ 81 modules transformed.
[vite]: Rollup failed to resolve import "@tiptap/prosemirror-tables" from "node_modules/frappe-ui/node_modules/@tiptap/extension-table/dist/tiptap-extension-table.esm.js".
This is most likely unintended because it can break your application at runtime.
If you do want to externalize this module explicitly add it to
`build.rollupOptions.external`
error during build:
Error: [vite]: Rollup failed to resolve import "@tiptap/prosemirror-tables" from "node_modules/frappe-ui/node_modules/@tiptap/extension-table/dist/tiptap-extension-table.esm.js".
This is most likely unintended because it can break your application at runtime.
If you do want to externalize this module explicitly add it to
`build.rollupOptions.external`
    at onRollupWarning (/workspace/development/frappe-bench/apps/sampleclone/frontend/node_modules/vite/dist/node/chunks/dep-0351185a.js:37915:19)
    at onwarn (/workspace/development/frappe-bench/apps/sampleclone/frontend/node_modules/vite/dist/node/chunks/dep-0351185a.js:37693:13)
    at Object.onwarn (/workspace/development/frappe-bench/apps/sampleclone/frontend/node_modules/rollup/dist/shared/rollup.js:23094:13)
    at ModuleLoader.handleResolveId (/workspace/development/frappe-bench/apps/sampleclone/frontend/node_modules/rollup/dist/shared/rollup.js:22376:26)
    at /workspace/development/frappe-bench/apps/sampleclone/frontend/node_modules/rollup/dist/shared/rollup.js:22353:26
[!] Error: unfinished hook action(s) on exit:
(vite:css) transform "/workspace/development/frappe-bench/apps/sampleclone/frontend/src/index.css"
(vite:css) transform "/workspace/development/frappe-bench/apps/sampleclone/frontend/node_modules/frappe-ui/src/components/Input.vue?vue&type=style&index=0&lang.css"
(vite:load-fallback) load "/workspace/development/frappe-bench/apps/sampleclone/frontend/node_modules/frappe-ui/node_modules/@popperjs/core/lib/createPopper.js"
(vite:load-fallback) load "/workspace/development/frappe-bench/apps/sampleclone/frontend/node_modules/frappe-ui/node_modules/@popperjs/core/lib/popper.js"
(vite:load-fallback) load "/workspace/development/frappe-bench/apps/sampleclone/frontend/node_modules/frappe-ui/node_modules/@popperjs/core/lib/popper-lite.js"
(vite:load-fallback) load "/workspace/development/frappe-bench/apps/sampleclone/frontend/node_modules/frappe-ui/node_modules/@tiptap/extension-table-cell/dist/tiptap-extension-table-cell.esm.js"
(vite:load-fallback) load "/workspace/development/frappe-bench/apps/sampleclone/frontend/node_modules/frappe-ui/node_modules/@tiptap/extension-table-header/dist/tiptap-extension-table-header.esm.js"
(vite:load-fallback) load "/workspace/development/frappe-bench/apps/sampleclone/frontend/node_modules/frappe-ui/node_modules/@tiptap/extension-table-row/dist/tiptap-extension-table-row.esm.js"
(vite:load-fallback) load "/workspace/development/frappe-bench/apps/sampleclone/frontend/node_modules/frappe-ui/src/components/TextEditor/image-extension.js"
(vite:load-fallback) load "/workspace/development/frappe-bench/apps/sampleclone/frontend/node_modules/frappe-ui/src/components/TextEditor/video-extension.js"
(vite:load-fallback) load "/workspace/development/frappe-bench/apps/sampleclone/frontend/node_modules/frappe-ui/node_modules/@tiptap/extension-link/dist/tiptap-extension-link.esm.js"
(vite:load-fallback) load "/workspace/development/frappe-bench/apps/sampleclone/frontend/node_modules/frappe-ui/node_modules/@tiptap/extension-typography/dist/tiptap-extension-typography.esm.js"
(vite:load-fallback) load "/workspace/development/frappe-bench/apps/sampleclone/frontend/node_modules/frappe-ui/node_modules/@tiptap/extension-text-style/dist/tiptap-extension-text-style.esm.js"
(vite:load-fallback) load "/workspace/development/frappe-bench/apps/sampleclone/frontend/node_modules/frappe-ui/node_modules/@tiptap/extension-highlight/dist/tiptap-extension-highlight.esm.js"
(vite:load-fallback) load "/workspace/development/frappe-bench/apps/sampleclone/frontend/node_modules/frappe-ui/node_modules/@tiptap/extension-color/dist/tiptap-extension-color.esm.js"
(vite:load-fallback) load "/workspace/development/frappe-bench/apps/sampleclone/frontend/node_modules/frappe-ui/src/components/TextEditor/mention.js"
(vite:load-fallback) load "/workspace/development/frappe-bench/apps/sampleclone/frontend/node_modules/frappe-ui/src/utils/markdown.js"
(vite:load-fallback) load "/workspace/development/frappe-bench/apps/sampleclone/frontend/node_modules/frappe-ui/node_modules/prosemirror-model/dist/index.js"
(vite:css) transform "/workspace/development/frappe-bench/apps/sampleclone/frontend/node_modules/frappe-ui/src/components/TextEditor/TextEditor.vue?vue&type=style&index=0&lang.css"
(vite:load-fallback) load "/workspace/development/frappe-bench/apps/sampleclone/frontend/node_modules/frappe-ui/src/components/TextEditor/utils.js"
(vite:load-fallback) load "/workspace/development/frappe-bench/apps/sampleclone/frontend/node_modules/frappe-ui/src/components/TextEditor/Menu.vue"
(vite:load-fallback) load "/workspace/development/frappe-bench/apps/sampleclone/frontend/node_modules/frappe-ui/src/resources/local.js"
(vite:load-fallback) load "/workspace/development/frappe-bench/apps/sampleclone/frontend/node_modules/frappe-ui/node_modules/socket.io-client/build/esm/index.js"

error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**Comment by skanel** [comment]
Please run this, and sorry for keep you waiting.

`npm i prosemirror-schema-list prosemirror-history prosemirror-dropcursor prosemirror-gapcursor prosemirror-keymap prosemirror-commands`
